# Generated by Django 4.2.5 on 2023-10-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField(max_length=3000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.users', verbose_name='author')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.subjects', verbose_name='subject')),
            ],
        ),
    ]
