# Generated by Django 4.2.5 on 2023-10-15 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_posts_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 19, 40, 53, 173849, tzinfo=datetime.timezone.utc), verbose_name='publish date'),
        ),
    ]
