# Generated by Django 4.2.5 on 2023-10-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjects', models.CharField(max_length=30)),
                ('Group', models.CharField(choices=[('Math', 'Math'), ('Experimental Sciences', 'Experimental Sciences'), ('LanguageA', 'Language Liturature'), ('LanguageB', 'Language acquisition'), ('Social Sciences', 'Social Sciences'), ('The Arts', 'the arts'), ('General', 'General'), ('DP core', 'DP core')], max_length=30)),
            ],
        ),
    ]
